server:
  host: "0.0.0.0"
  port: 8080

logging:
  level: "info"

auth:
  enabled: true
  issuer: "http://localhost:8081/realms/myrealm"
  audience: "account"
  cache_ttl: "10m"

ratelimit:
  enabled: true
  backend: "redis" # or "memory"
  redis_address: "localhost:6379"
  default:
    requests: 100
    window: "1m"
  groups:
    "testgroup":
      name: "testgroup"
      requests: 5
      window: "1m"
    "premium-users":
      name: "premium-users"
      requests: 1000
      window: "1h"

strategies:
  - name: "default"
    providers:
      - "openai"

providers:
  - name: "openai"
    enabled: true
    target_url: "http://mock-llm:8080"
    api_key: "${OPENAI_API_KEY}"
    timeout: 60s
    max_retries: 3
    models:
      - name: "gpt-4"
        allowed_groups: ["testgroup", "premium-users"]
      - name: "gpt-3.5-turbo"
        allowed_groups: ["testgroup"]