[connections.keycloak]
# This is the URL the user's browser will be redirected to.
# It points to the Keycloak service exposed by the docker-compose file.
server_metadata_url = "http://localhost:8180/realms/llm-test-realm/.well-known/openid-configuration"

# This is the client ID we will create in the setup_keycloak.sh script.
client_id = "token-app"

# This is the callback URL for the Streamlit app after the user logs in.
# It must be listed in the client's "Valid Redirect URIs" in Keycloak.
redirect_uri = "http://localhost:8501/oauth2callback"
