[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "a-random-secret-key" # This should be a strong, randomly generated string

[auth.keycloak]
server_metadata_url = "http://keycloak:8080/realms/llm-test-realm/.well-known/openid-configuration"
client_id = "token-app"
client_secret = ""